# Generated by Django 5.2.17 on 2026-09-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artworks_projects_experience_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
