# Generated by Django 5.2.17 on 2026-09-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='category',
            field=models.CharField(default='uncategorized', max_length=50),
        ),
    ]
