# Generated by Django 5.2.17 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_artworks_id_alter_projects_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworks',
            options={'ordering': ['id'], 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['id'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='artworks',
            name='image',
            field=models.CharField(blank=True, help_text='Kosong jika berupa video', max_length=255),
        ),
        migrations.AlterField(
            model_name='artworks',
            name='video',
            field=models.CharField(blank=True, help_text='Kosong jika berupa gambar', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.CharField(help_text='Path statis, mis. /static/img/cover-*.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, help_text='External Game URL', max_length=255),
        ),
    ]
